%% Load global varibales. Kamuran Turksoy
save prevdata gs kj...
armband_data_with_time ee phys_act sleep gsr...
IOB_total bolus_insulin bolus_insulin_meal basal_insulin...
meal_states meal_covariance meal_bolus_amount meal_detection...
meal_detection_time correction_bolus_amount correction_detection...
correction_detection_time correction_limit...
meal_g_basal meal_gpc_gs_slope_degree meal_gpc_mu...
phi phi_ee phi_gsr...
armax_parameters armax_covariance armax_lamda armax_err...
arma_parameters_ee arma_lamda_ee arma_covariance_ee arma_err_ee...
arma_parameters_gsr arma_lamda_gsr arma_covariance_gsr arma_err_gsr...
A_state A_state_ee A_state_gsr...
C_state C_state_ee C_state_gsr...
B_state K_state K_state_ee K_state_gsr...
M L L_ee L_gsr M_ee M_gsr...
X_state X_state_ee X_state_gsr...
ee_prediction gsr_prediction g_prediction...
reference_glucose insulin_sensitivity_constant IOB_prediction...
maximum_insulin total_daily_unit insulin_sensitivity_factor...
body_weight...
hypo_threshold hypo_slope_degree hypo_alarm hypo_alarm_old...
carb_amount carb_type hypo_phase hypo_phase_old...
repeated_immediate_alarm mdata batch_CL...
bolus_insulin_calculated basal_insulin_calculated...
auto_backup_time...
CGM_retuning_with_noise_generator CGM_retuning_without_noise_generator...
type_of_exercise type_of_entry fault fault_reason


