/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dias;

import Jama.Matrix;
import javax.mail.MessagingException;

/**
 *
 * @author User
 */
public class DIAS {

    //Parameter: excel files to save/load variables
    //TODO make sure files exist in the given path
    public static final String excelFilePath = "C:\\Users\\Cat\\Desktop\\Java-MATLAB";
    //Parameter: File for Bodymedia read values
    //TODO make sure this file is the same as the xls generated by BodyMedia
    public static final String bodymediaFileUrl = "C:\\Users\\Cat\\Desktop\\Java-MATLAB\\Matlab\\JDRF17_04222015 TO 04272015_ARMBAND.xls";

    //Parameter: Email to receive messages
    public static final String[] privateMails = new String[]{"caterina.lazaro@gmail.com"};

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws MessagingException, Exception {
        //Start Graphical interface
        new GUI().setVisible(true);

        //  ChocaNonLinear ch = new ChocaNonLinear ();
        //   ch.Choca();
    }

    //////////////////////////////For show the result in Matrix Class/////////////////////////////////////////////////////////////////////////////////////////
    public static void printMatrix(Matrix m, String name) {
        System.out.print("\n " + name + ": \n{");
        for (double[] row : m.getArray()) {
            for (double val : row) {
                System.out.print(" " + val);
            }
            System.out.println();
        }
        System.out.println("}");
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  

    public static int[] lastvaluereturnx(Matrix s) {
        int lastvaluex = 0;
        int lastvaluey = 0;

        for (int i = 0; i < s.getColumnDimension(); i++) {
            for (int j = 0; j < s.getRowDimension(); j++) {
                if (s.get(i, j) != 0) {
                    lastvaluex = i;
                    lastvaluey = j;
                }
            }
        }
        int[] resultlocation = new int[2];
        resultlocation[0] = lastvaluex;
        resultlocation[1] = lastvaluey;

        return resultlocation;
    }

}
